spring:
  application:
    name: safedog
 
  datasource:
    url: jdbc:mysql://localhost:3306/SAFEDOG
    username: root
    password: 3rgu3z
 
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
